name: IP Generator

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  daily-execution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script
        run: |
          python script.py

      - name: Upload files to repository
        uses: actions/upload-artifact@v4
        with:
          name: files
          path: |
            ips.txt
            README.md

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Update files" || echo "No changes to commit"
          git push origin main
